### PR TITLE
Build 1.13

### PR DESCRIPTION
**Pull request by pierrsc**
One of my packages needs this version of routes, would you be able to create a separate branch for the 1.x series
and merge it?

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pierrsc** [comment]
@conda-forge-admin, please serenader

**Comment by pierrsc** [comment]
@conda-forge-admin, please rerender

**Comment by pierrsc** [comment]
@pmlandwehr, the build 1.13 of routes is ready for review/merge. I need an older version for one of the packages that I am using.

**Comment by pmlandwehr** [comment]
I've just made a new [branch for 1.13](https://github.com/conda-forge/routes-feedstock/tree/1.13). Can you submit your pull to that branch instead? We'd like to keep master up to date.

**Pull request closed without merging**
